version: '3.8'

services:
  mstodo_web:
    build: .
    container_name: mstodo_web
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Seoul
      - MS_CLIENT_ID=
      - MS_CLIENT_SECRET=
